src/eos-updater-util.c
Or we'll hit a critical assertion when calling into
ostree_sysroot_get_merge_deployment() when we're not on an OSTree
system.
endlessm/eos-shell#5087
=> updater: bail out if we're not on a booted OSTree deployment

src/eos-updater-apply.c
This prevents multiple processes (e.g. eos-updater and ostree admin
upgrade) from concurrently deploying, which tends to fail.
[endlessm/eos-shell#5756]
=> Take sysroot lock during apply

configure.ac
libsystemd-journal has been merged into libsystemd on the newer systemd
(229) we are shipping on eos 2.7.
https://phabricator.endlessm.com/T6363
=> Update systemd dependency

src/eos-updater-apply.c, src/eos-updater-fetch.c, src/eos-updater-poll.c, src/eos-updater-util.c, src/eos-updater-util.h, src/eos-updater.c, src/eos-updater.xml
Keep track of the original update refspec so it can be deleted and not keep a reference to a no longer wanted tree.
https://phabricator.endlessm.com/T11010
=> Cleanup old remote ref

src/Makefile.am, src/eos-updater-live-boot.c, src/eos-updater-live-boot.h, src/eos-updater-util.c, src/eos-updater.c
eos-autoupdater.timer is already stopped and masked from the initramfs,
but this prevents any updates being fetched or installed.
The rationale here is that endless.live_boot sessions have a read-only
filesystem, with overlay+tmpfs mounted over directories which need to be
read-write. Running an ostree update on such a system is at best
wasteful and frustrating (it will be discarded as soon as you reboot, so
can never be used), and at worst disastrous (it fills /run, because
hardlinking files on overlay requires copying the file from the lower to
the upper filesystem, and your live system breaks until you reboot).
https://phabricator.endlessm.com/T13951
=> Disable all update steps on live sessions

src/eos-autoupdater.c, src/eos-updater-apply.c, src/eos-updater-fetch.c, src/eos-updater-live-boot.c, src/eos-updater-live-boot.h, src/eos-updater-poll.c, src/eos-updater-util.c, src/eos-updater-util.h, src/eos-updater.c, src/eos-updater.xml
As described in the XML comments, ErrorCode is actually totally useless for
determining what error has occurred. It is the `code` field of a
`GError`, but without the `domain` field you have no way of knowing if
`1` means EOS_UPDATER_ERROR_LIVE_BOOT or G_IO_ERROR_NOT_FOUND (which
happens in practice on converted systems).
Exposing a fully-qualified error name in a property is consistent with the
way errors are reported from D-Bus methods. There's also prior art: we used
this approach in Telepathy after learning the hard way that integers are no
good for extensibility.
EOS_UPDATER_ERROR_LIVE_BOOT is reported as follows:
ErrorCode: uint32 1
ErrorMessage: 'Updater disabled on live systems'
ErrorName: 'com.endlessm.Updater.Error.LiveBoot'
On converted systems, we report this rather ugly …
=> Add an ErrorName D-Bus property

.gitignore, autogen.sh, configure.ac, src/eos-updater-util.c
Ensure that the error details appear in the journal, so that it’s easier
to debug problems later, when we can’t necessarily query the error state
of eos-updater over D-Bus.
https://phabricator.endlessm.com/T14640
---
This also includes some changes to drop the gnome-common dependency, which made it a bit easier for me to compile eos-updater.
=> T14640 — eos-updater-util: Log when entering or leaving an error state

libeos-updater-util/tests/config.c
Root can access everything, so checking that a file returns EACCES is
not going to give us the result we expect. This happens if the tests are
run as root, which happens in Jenkins.
https://phabricator.endlessm.com/T15545
=> tests: Skip a permissions test if running as root

src/eos-updater.c
If getting the booted checksum fails, consistently return
EOS_UPDATER_ERROR_NOT_OSTREE_SYSTEM, rather than a G_IO_ERROR which is
not suitable for sending over D-Bus. On a dev-converted system, getting
the booted checksum will fail as we are not booted into an OSTree
deployment.
https://phabricator.endlessm.com/T15644
=> eos-updater: Consistently error out at startup if not using OSTree

libeos-updater-util/tests/config.c
Previously this was testing for whether the effective UID was root, on
the assumption that root was the only user able to bypass DAC checks on
file permissions. However, on Jenkins it seems this is not the case —
there might be some UID remapping going on, or the jenkins user might
have CAP_DAC_OVERRIDE. In any case, the check can be improved by testing
to see if the user can read the ‘unreadable file’. If they can, skip the
test.
The test is run frequently enough locally by anyone developing
eos-updater that it will still be run enough to catch problems with the
code.
https://phabricator.endlessm.com/T15545
=> tests: Improve check for skipping ‘unreadable file’ test

src/eos-repo-server.c
If the modified repository configuration can’t be written, a warning is
printed. Ensure that warning contains the actual error message.
https://phabricator.endlessm.com/T15544
---
Follow up to https://github.com/endlessm/eos-updater/pull/60#discussion_r102995381.
=> eos-repo-server: Print error details in a warning message

data/docs/eos-autoupdater.conf.5, data/docs/eos-update-server.conf.5, data/docs/eos-updater.conf.5
They’re in section 5, and I forgot that the section is specified in the
page header, as well as in the filename and the installation path.
man, this is such a pain.
https://phabricator.endlessm.com/T15702
=> docs: Fix man sections for .conf man pages

configure.ac, src/docs/eos-update-server.8
This one’s a little less overloaded (not officially or unofficially
assigned to anything).
https://phabricator.endlessm.com/T15894
=> build: Change default LAN port from 12345 to 43381

src/eos-updater-poll-common.c, src/eos-updater-poll-lan.c
If eos-updater polled for updates from another computer on the local
network which has the same (or an older) OSTree ref deployed as the
current computer, eos-updater would crash.
This never actually caused a problem, because eos-updater not running is
essentially equivalent to it running and being in the Ready state, which
is the state it would have switched back to after finding no newer
OSTree commits to fetch from the other computer. It would have caused
problems on networks where there’s more than one computer advertising
updates; but that’s not a configuration we support yet.
In any case, crashing is bad. Fix it. The confusion resulted from
is_checksum_an_update() returning TRUE while explicitly not returning
something in one of its out parameters, and the caller not handling this …
=> eos-updater-poll-lan: Fix crash polling a LAN source on the same ref

debian/eos-updater.postinst
Previous versions of eos-updater provided eos-updater.{service,timer} as
aliases for eos-autoupdater.{service,timer}. The latest versions provide
eos-updater.service as an independent service file (for binding the
com.endlessm.Updater D-Bus service to systemd), and no
eos-updater.timer.
However, existing EOS deployments might have left-over
eos-updater.{service,timer} files in /etc/systemd/system due to
previously editing them. They won’t match the new unit file setup, and
will override it, causing eos-updater to not start on demand.
Fix that by deleting them in an eos-updater.postinst script. This will
only take effect on dev-converted systems — on non-dev-converted
systems, we have to rely on people having not edited the unit files. …
=> debian: Add postinst script to delete outdated eos-updater.service

debian/control
This is a follow-up commit for 7234b8ef which bumps our libostree
package dependency to the one including the new symbol. Note that this
doesn’t bump the dependency in configure.ac for the reasons mentioned in
commit 7234b8ef.
https://phabricator.endlessm.com/T15909
=> debian: Bump libostree dependency for new archive-z2 symbol

eos-updater-avahi/eos-updater-avahi.service.in
Previously, the eos-updater-avahi.service unit would only be triggered
when any of the paths watched by eos-updater-avahi.path were changed.
This isn’t actually what we want — we also want it to be triggered on
boot when those paths aren’t changed, just to sync the state of the
Avahi service file.
Add a WantedBy=multi-user.target to achieve that; and correctly add the
Wants=avahi-daemon.service relation to ensure this does pull the Avahi
daemon into the boot too.
https://phabricator.endlessm.com/T16000
=> eos-updater-avahi: Add Wants= dependency from multi-user.target

src/eos-repo-server.c, src/eos-update-server.c
This failure was only apparent when using keepalive connections to the server (or if the server started listening but was never sent a request).
https://phabricator.endlessm.com/T16387
=> T16387 test failure

configure.ac, debian/control, src/eos-autoupdater.c
The libnm-glib library is deprecated.
https://phabricator.endlessm.com/T15813
Unfortunately `make check` does not pass for me neither on my branch nor on the current master branch. Will need to investigate.
=> autoupdater: Port to libnm

src/eos-autoupdater.c
Only write it if a randomised delay is configured, otherwise our first
check for updates will be delayed by the IntervalDays period. When we do
write it, discount the normal IntervalDays period so that the update
will be performed after the RandomizedDelayDays period *only*.
https://phabricator.endlessm.com/T16643
=> eos-autoupdater: Don’t normally write stamp file on first boot

src/eos-updater-poll.c, src/eos-updater.c
When test mode is enabled in the first boot environment, overlay file
systems are mounted on top of everything (including /ostree), which
breaks OSTree. (This is expected.)
This causes libostree to return an error from ostree_sysroot_load(),
which we were not correctly handling, and hence were passing through the
wrong error domain over eos-updater’s D-Bus interface. This caused an
error message to appear in the UI when it wasn’t supposed to.
https://phabricator.endlessm.com/T16574
=> eos-updater: Handle G_IO_ERROR_FAILED when running in FBE test mode

eos-update-server/eos-update-server.c, libeos-update-server/config.c, libeos-updater-util/tests/Makefile.am, libeos-updater-util/tests/util.c, libeos-updater-util/util.c, libeos-updater-util/util.h, src/eos-autoupdater.c, src/eos-updater-poll-lan.c
That thing got copy-pasted all over the place and I was about to do it
once again. Better just split it to function and add test to verify I
did not break anything.
=> util: Add functions for parsing the entire string as a number

debian/control
The tests of eos-updater package depend on
ostree-trivial-httpd, which is provided by
ostree-test package.
This commit adds ostree-test as a build-time
dependency, so that Jenkins build passes all
the tests.
https://phabricator.endlessm.com/T17204
=> Add ostree-tests as a build dependency

src/eos-updater-apply.c, src/eos-updater-fetch.c, tests/Makefile.am, tests/eos-test-convenience.c, tests/eos-test-convenience.h, tests/eos-test-utils.c, tests/eos-test-utils.h, tests/ostree-spawn.c, tests/ostree-spawn.h, tests/spawn-utils.c, tests/spawn-utils.h, tests/test-update-broken-delta.c, tests/test-update-cleanup-workaround.c
The sysroot cleanup happens after the successful deployment. The
failures are likely the result of the concurrent prunes that happened
earlier.
So tell ostree to skip cleanup and perform it ourselves later, so we
can simply log an error, but still report a success as the "apply"
command is mostly about creating a new deployment, not doing the
cleanup.
https://phabricator.endlessm.com/T16958
=> eos-updater-apply: Workaround failures during sysroot cleanup

src/eos-updater-fetch.c
This information is reported in the eos-updater D-Bus interface, but
it’s useful to have it in the journal too.
https://phabricator.endlessm.com/T19272
=> fetch: Output slightly more information on a fetch failure

src/eos-updater-fetch.c, src/eos-updater-object.c
The GError here is using g_autoptr(), meaning it gets freed
automatically on exit from the function — but g_propagate_error() takes
ownership of it too, resulting in a double-free and some corrupted
failure messages being reported to the user.
---
Reported by @wjt on #updater on Slack.
=> src/fetch: Fix a double-free of a GError leading to corrupted messages

libeos-updater-util/ostree-bloom.c, tests/spawn-utils.h
Version of #110 for eos3.3. Doesn’t depend on the GLib fixes which #110 does.
https://phabricator.endlessm.com/T19388
=> T19388: Fix OSTree bloom hashing (and tests) on ARM (for eos3.3)

libeos-updater-util/extensions.c, libeos-updater-util/extensions.h, src/eos-updater-poll-common.c, tests/eos-test-utils.c
With the new unsigned summary support and ostree-metadata branch, we
don’t need refs.d directories. They were never supported by our
infrastructure anyway, so were never used in practice.
https://phabricator.endlessm.com/T15926
---
This depends on https://github.com/endlessm/eos-updater/pull/113 being merged first, since it’s stacked on top of that. The only relevant commit in this PR is the top-most one.
=> lib/extensions: Drop support for refs.d directories

debian/control
Seems like dh_python is not doing its job and listing the Python
dependencies automatically. List the dependencies for
eos-updater-prepare-volume and eos-updater-ctl manually.
https://phabricator.endlessm.com/T19293
=> debian: Add missing Python dependencies for eos-updater-prepare-volume

debian/control
Since the tests are run at build time, we need to depend on the Python
modules they use (primarily gobject-introspection) in order to
successfully build eos-updater.
The eos-updater-tests package additionally needs to depend on
eos-updater-tools for eos-updater-prepare-volume, which it shells out to
at times.
https://phabricator.endlessm.com/T19293
=> debian: Add Python dependencies for tests to build-depends

eos-updater-prepare-volume/eos-updater-prepare-volume
Handle errors in listing the available installations, which can happen
because libflatpak tries to ensure a repository exists for each location
it checks — if the user doesn’t have permission to create the
repository, this can fail. Another error can be returned if
get_system_installations() can’t find *any* accessible system
installations.
https://phabricator.endlessm.com/T19293
=> eos-updater-prepare-volume: Improve FlatpakInstallation error handling

libeos-update-server/repo.c
Use gsize instead of size_t for consistency, and use a better variable
name than "len". No functional changes.
=> libeos-update-server/repo: Clean up /refs/heads handler

libeos-update-server/repo.c
When peers request collection refs from each other, they can use the
format /refs/mirrors/$collection_id/$ref to avoid having to assume that
the remote name is the same on both machines. This commit makes
eos-update-server handle these requests either directly if such a file
exists or by redirecting them to /refs/remotes/$remote_name/$ref if
the remote $remote_name has a collection ID that matches $collection_id.
https://phabricator.endlessm.com/T18718
=> libeos-update-server: Support /refs/mirrors/ requests

src/eos-updater-poll.c
There was one more printf placeholder than parameters passed to
g_debug(), and for some reason this wasn’t noticed as a compiler
warning. It could intermittently cause crashes, depending on what’s on
the stack at the time (strlen() would be called on it).
https://phabricator.endlessm.com/T19367
=> src: Fix crash caused by incorrect number of printf() parameters

libeos-update-server/repo.c
Serving mirror refs from a remote other than the one set as
EusRepo:served-remote was broken due to passing the wrong remote name
around. Fix that.
https://phabricator.endlessm.com/T18718
=> libeos-update-server: Fix serving mirror refs from non-default remotes

data/docs/eos-updater.conf.5, eos-updater-prepare-volume/docs/eos-updater-prepare-volume.8
You no longer need a `[Source "volume"]` section, since USB sticks are
detected and enumerated automatically.
=> docs: Drop outdated documentation for pulling from USB sticks

libeos-updater-util/tests/Makefile.am
We don’t care about the coverage of the tests themselves, just the code
they’re testing.
=> libeos-updater-util: Remove code coverage from unit test code

test-common/utils.c
See
https://github.com/endlessm/eos-updater/pull/129#discussion_r157124000.
=> tests: Add a comment explaining why we use a regex

Makefile.am, debian/eos-updater-tools.install, debian/eos-updater.install, debian/rules, eos-updater-flatpak-installer/docs/eos-updater-flatpak-autoinstall.d.5, eos-updater-flatpak-installer/docs/eos-updater-flatpak-installer.8, eos-updater-flatpak-installer/eos-updater-autoinstall.schema.json, eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in, eos-updater-flatpak-installer/main.c
(**This doesn’t really need reviewing; it’s the results of my review of one of the commits on #129, which I’m pushing here to get Jenkins to test run the build.**)
This binary uses the functions in libeos-updater-flatpak-installer
to actually install flatpaks on reboot. It also has a "check" mode
which checks if the flatpak actions we claim to have applied are actually
fully-up-to-date on the system.
(Modified by Philip Withnall to improve formatting on man pages and fix
a few minor bugs found during review.)
=> installer: Add eos-updater-flatpak-installer

libeos-updater-util/flatpak.c
Otherwise when eos-updater-flatpak-installer has nothing to do, its
output looks a little funny.
=> util/flatpak: Print ‘(None)’ when formatting empty lists

src/eos-updater-poll-common.c, src/eos-updater-poll-common.h, src/eos-updater-poll-main.c, src/eos-updater-poll.c, test-common/utils.c, tests/Makefile.am, tests/test-update-refspec-checkpoint.c
(**No need to review this unless really necessary; I’ve just reviewed it. I’m pushing this here to get Jenkins to test it.**)
Use "eos.checkpoint-target" as a metadata item on a commit with
the name of a new refspec to pull from next time the updater
is run with that commit deployed.
This allows for "checkpoint commits", eg, stop updating the OS
at refspec eos-history-v1 and set its "checkpoint target" to
eos-history-v2. When eos-history-v1 is deployed, the next time
we fetch we'll fetch from eos-history-v2 instead and then from
that point forward will continue to fetch from eos-history-v2
since that was the booted refspec.
(Modified by Philip Withnall to fix some minor issues found during code
review.)
https://phabricator.endlessm.com/T19437
=> poll: Allow distributors to override the refspec to update from

eos-updater-flatpak-installer/eos-updater-autoinstall.schema.json
• Remove trailing commas (invalid JSON)
• Remove duplicate `required` element
• Fix names of filters (the specification doesn’t pluralise them)
The resulting schema is valid according to:
json-schema-validate *.schema.json
using Walbottle (https://gitlab.com/walbottle/walbottle).
=> flatpak: Various small fixes to the autoinstall JSON schema

src/eos-updater-poll.c
If the OstreeRepoFinderAvahi instance fails to start (which can
happen if libostree is compiled without avahi support), eos-updater hits
an assertion failure when it passes an empty array to
ostree_repo_find_remotes_async. Change it to instead print a meaningful
error message.
https://phabricator.endlessm.com/T19367
=> poll: Fail gracefully w/o OstreeRepoFinderAvahi

libeos-updater-util/flatpak.c, libeos-updater-util/tests/flatpak.c
This means explicitly passing the architecture to
FlatpakRef's constructor so that we can pass an overridden one.
=> util: Override architecture during testing

src/eos-updater-fetch.c
Fix checks on collection IDs vs remote names from the autoinstall JSON files. See https://phabricator.endlessm.com/T20812.
=> T20812 flatpak checks

src/eos-updater-apply.c, src/eos-updater-fetch.c, src/eos-updater-poll.c
This does not make things fully thread safe. In particular, the poll
operation is still a complete mess, and the fetch operation still has
some non-thread-safe accesses to the EosUpdaterData struct. The apply
operation should be thread-safe now though.
All the operations (poll, fetch, apply) use a single worker thread each
to do the bulk of their work. These were previously passed pointers to
the EosUpdater and EosUpdaterData structs, which are also used in the
main thread. This was not thread safe.
Fix that by adding a per-operation struct (ApplyData or FetchData) into
which the data needed by the worker thread is copied before the main
thread forks. In the case of the fetch operation, this includes an
OstreeAsyncProgress object, which reports progress data back to the main
thread. This …
=> src: Improvements to thread safety for apply and fetch operations

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
eos-extra-settled.target is generated with a dependency on the SD
card being mounted at /var/endless-extra on "split" systems which
have their Flatpaks on the SD card. Adding this dependency makes
sure that the Flatpak system installation is ready/accessible
before we try and deploy the Flatpaks - although it has the side
effect that this unit won't complete on systems where the SD card
is missing.
https://phabricator.endlessm.com/T20696
=> flatpak-updater: add eos-extra-settled.target as pre-requisite

eos-updater-prepare-volume/docs/eos-updater-prepare-volume.8, eos-updater-prepare-volume/eos-updater-prepare-volume
Hopefully make it a little clearer what format the flatpak refs are
expected in for the apps to copy to the USB stick.
https://phabricator.endlessm.com/T20926
=> docs: Clarify command line format for eos-updater-prepare-volume

src/eos-updater-poll-common.c, src/eos-updater-poll-common.h
Potential fix for https://phabricator.endlessm.com/T20958. Only compile tested. See the commit messages for details.
=> T20958 Fix NULL remote names in refspecs

src/eos-updater-fetch.c
If a refspec is of the form "some-ref" rather than
"remote-name:some-ref", ostree_parse_refspec() returns NULL for the
remote parameter, so check for that possibility in content_fetch_old().
=> fetch: Check for invalid refspec

eos-updater-prepare-volume/eos-updater-prepare-volume
As with previous commits, this adds robustness to
eos-updater-prepare-volume in case the origin is not configured
correctly (this is not expected to happen).
https://phabricator.endlessm.com/T20958
=> eos-updater-prepare-volume: Handle empty remote name from parse_refspec

libeos-updater-flatpak-installer/perform-flatpak-actions.c
Always printed "is installed" regardless of return value of function.
=> flatpak-installer: tidy up debug messages

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
Upgrade Wants to Requires so the unit can't run without the /var/endless-extra
being settled. Use local-fs.target instead of ostree-remount.service.
https://phabricator.endlessm.com/T20696
=> flatpak-installer: modify unit to use After/Requires

debian/control
Since the updater now queries the download scheduler to see if it is
allowed to download, it should require that the scheduler is actually
installed.
Critically, this will pull mogwai-scheduled into the set of packages
installed by default on base images.
https://phabricator.endlessm.com/T20396
=> debian: Make eos-updater depend on mogwai-scheduled

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
On unconverted systems, /home is a symlink to /var/home; /var/home is a
symlink to /sysroot/home. The /home -> /var/home symlink is part of the
ostree; the /var/home -> /sysroot/home symlink is managed by
systemd-tmpfiles:
/usr/lib/tmpfiles.d/ostree.conf:L /var/home - - - - ../sysroot/home
/usr/lib/tmpfiles.d/home.conf:Q /home 0755 - - -
(The home.conf line for /home comes from the systemd package, and causes the
"already exists and is not a directory" warning below.)
With the current ordering constraints, these two services may (and do)
run concurrently. This, in combination with ProtectHome=yes in this
unit, causes launching this service to fail:
systemd[1]: Starting Endless OS Post-Boot Flatpak Installer...
systemd[1]: Starting Create Volatile Files and Directories... …
=> eos-updater-flatpak-installer: run after systemd-tmpfiles-setup

src/eos-updater-ctl
Before:
======= Properties =======
State: Ready
CurrentID: '4b4e0fb003bae61d18152376a597675063c2dd1e3561ffe4eec8cd637f533f62'
DownloadSize: int64 0
DownloadedBytes: int64 0
ErrorCode: uint32 0
ErrorMessage: ''
ErrorName: ''
FullDownloadSize: int64 0
FullUnpackedSize: int64 0
OriginalRefspec: ''
UnpackedSize: int64 0
UpdateID: ''
UpdateLabel: ''
UpdateMessage: ''
UpdateRefspec: ''
After:
======= Properties =======
State: Ready
CurrentID: '4b4e0fb003bae61d18152376a597675063c2dd1e3561ffe4eec8cd637f533f62'
DownloadSize: int64 0
DownloadedBytes: int64 0
ErrorCode: uint32 0
ErrorMessage: ''
ErrorName: ''
FullDownloadSize: int64 0
FullUnpackedSize: int64 0
OriginalRefspec: ''
UnpackedSize: int64 0
UpdateID: ''
UpdateLabel: ''
UpdateMessage: ''
UpdateRefspec: ''
I think this is easier to skim, …
=> eos-updater-ctl: right-align property names

src/eos-updater-ctl
I broke this in #174. Sorry.
Any preferred way to check this at build time? One way would be to add a test case which just runs s `python3 -m py_compile eos-updater-ctl`. Another way would be to build-depend on a linter and run that. A third way would be to rename to `eos-updater-ctl.in` and do:
eos-updater-ctl: eos-updater-ctl.in
$(AM_V_GEN) python3 -m py_compile $< && cp -a $< $@
=> eos-updater-ctl: fix syntax

debian/control, src/Makefile.am, src/eos-updater-ctl
This is implemented as a build step, not a test, to increase the likelihood of it being run. I looked at adding it as an installed test in tests/ but installed tests are not run at build time.
I also took the liberty of fixing the (very few) warnings raised by flake8, my conservative Python linter of choice. While it does have some (IMO reasonable) opinions about line length and indentation, it can also detect many cases of (for example) referencing variables before they are defined. I'd suggest making `python3-flake8` a build-dependency and running it against `eos-updater-ctl` rather than invoking `eos-updater-ctl --help`, but I have not since this has already been deemed unpopular!
=> Ensure eos-updater-ctl compiles, by running it

src/eos-updater-ctl
This fixes a warning which @GeorgesStavracas was seeing when using `eos-updater-ctl monitor`.
=> Minor fixes to eos-updater-ctl

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
As identified, this is required for certain ostree operations
to work.
https://phabricator.endlessm.com/T21751
=> systemd: Remove the @chown system call group from the blacklist

src/com.endlessm.Updater.xml, src/eos-updater-poll-common.c, src/eos-updater-poll-common.h, src/eos-updater-poll.c, test-common/utils.c, test-common/utils.h, tests/test-update-direct.c
We now have the update version added to the commit metadata, so this
patch retrieves it and also adds the matching property to the dbus
interface.
https://phabricator.endlessm.com/T21610
=> Provide the update version property

eos-updater-flatpak-installer/docs/eos-updater-flatpak-autoinstall.d.5
The branch addition in 0f5d2770de8bad982187bdaeda69b485a7ba5658 was
supposed to be bolded, but the inline \fB directive was not written
correctly.
=> docs: Fix eos-updater-flatpak-autoinstall.d.5 page

eos-updater-flatpak-installer/docs/eos-updater-flatpak-installer.8
In eos-updater-flatpak-installer.8, there's a reference to an "apply"
mode but the mode is actually called "perform".
=> docs: Fix an erroneous reference to --mode=apply

src/eos-updater-fetch.c
The value for the OS updates priority is equal to what's expected for
this type of updates in GNOME Software, so it sets the appropriate
priority to app updates (Mogwai's checks eos-updater and GNOME
Software's priorities together).
https://phabricator.endlessm.com/T21327
=> fetch: Set schedule entry's priority

configure.ac
Welcome to 2018! This works really well with g_autoptr(), which we’ve
been using for a while.
I don’t plan to port the code from -Wdeclaration-after-statement to
-Wno-declaration-after-statement; but any new code or modifications made
after this commit should use declarations after statements where
appropriate.
=> build: Allow declarations after statements

libeos-updater-util/config.c, libeos-updater-util/tests/config.c
If loading an EuuConfigFile with a GResource, but none of the listed
files existing on the file system, it would hit an assertion failure.
Fix the special case handling of the GResource so that this works.
Adapted from a patch in https://phabricator.endlessm.com/T21619.
=> libeuu: Fix using EuuConfigFile with just the GResource

src/eos-updater-poll.c, test-common/convenience.c, test-common/utils.c, test-common/utils.h, tests/test-update-direct.c, tests/test-update-from-lan.c, tests/test-update-from-main.c, tests/test-update-from-volume.c, tests/test-update-refspec-checkpoint.c
Previously we would always unconditionally follow the upgrade refspec
if we were booted into a commit that had the update refspec as part
of its metadata. However, such an approach means that the client must
always be able to use the current updater on the checkpoint commit
to upgrade to the most recent commit. This leaves very little room
for error in case the updater on the current commit is not able
to process the new upgrade (for instance, incorrectly configured
flatpak remotes).
Considering that, we might want to "fix" the updater again before
we try upgrading on the branch that really requires it. That can
be done by adding new commits to the currently booted branch. However,
if we do that we need the updater to pay attention to the currently
booted branch and not the "upgrade" …
=> T22295: Check booted branch first before following update refspec

Makefile.am, configure.ac, debian/control, debian/eos-updater.install, debian/gir1.2-eos-updater-0.install, eos-updater-flatpak-installer/docs/eos-updater-flatpak-installer.8, eos-updater-flatpak-installer/main.c, libeos-updater-flatpak-installer/determine-flatpak-actions.c, libeos-updater-util/config.c, libeos-updater-util/flatpak.h
These commits had to broken off from the other T21756 commits because if I add EosUpdaterUtil-0 to `libeos_updater_flatpak_installer_EosUpdaterFlatpakInstaller_@EUFI_API_VERSION@_gir_INCLUDES` in the same commit that adds `EosUpdaterUtil-0.gir` as a target the build fails because the gir isn't installed at build time. So after this is merged, https://github.com/endlessm/eos-updater/pull/188 will be able to have that dependency.
=> T21756 preparation

src/eos-updater-poll-common.c, tests/test-update-refspec-checkpoint.c
The eos.checkpoint-target commit metadata is created on the server side
while the remote is a property of the client's configuration. Following
a remote specified in the metadata would almost certainly be wrong and
provide the server with the ability to switch a client's remote.
Instead, only take the ref from the metadata like the
ostree.endoflife-rebase handling. If a full refspec with remote is
included, the remote is ignored and a warning is issued.
https://phabricator.endlessm.com/T19437
=> poll-common: Operate on checkpoint refs, not refspecs

src/eos-updater-poll-common.c
If the caller passed in collection_ref_to_upgrade_on, then it needs to
be set even if it's NULL in the case where there's no collection ID set
for the remote.
The `g_autoptr` is overkill, but I thought I'd just make it safe in case anything more clever needs to be done here in the future.
https://phabricator.endlessm.com/T19437
=> poll-common: Always set collection ref out param

eos-updater/apply.c, tests/test-update-from-main.c, tests/test-update-refspec-checkpoint.c
This is mostly cosmetic since the only time the remote branches option
is used is when a pull is done with no refs specified. Still, people
expect it to match the ref in the origin refspec, and changing it to
match prevents inadvertently pulling an unused ref that would occupy
disk space. Errors from the option update are ignored since it has no
effect on the actual upgrade.
https://phabricator.endlessm.com/T22477
=> eos-updater-apply: Set remote branches option after deploy

eos-updater/poll-common.c, eos-updater/poll-common.h, eos-updater/poll.c, tests/test-update-refspec-checkpoint.c
Previously we checked if the commit timestamp was always greater than
the booted commit timestamp before pulling it. This won't work in
the case that a commit is made on a new branch (1), then we make
another commit on the old branch (2) with a checkpoint pointing
to then new branch.
https://phabricator.endlessm.com/T22498
=> poll: Don't treat move to older commit on new branch as a downgrade

Makefile.am, eos-updater-flatpak-installer/main.c, eos-updater-prepare-volume/docs/eos-updater-prepare-volume.8, eos-updater-prepare-volume/eos-updater-prepare-volume, libeos-updater-flatpak-installer/determine-flatpak-actions.c, libeos-updater-flatpak-installer/installer.h, libeos-updater-flatpak-installer/perform-flatpak-actions.c, libeos-updater-flatpak-installer/tests/installer.c, libeos-updater-util/config.c, libeos-updater-util/flatpak.c, libeos-updater-util/flatpak.h, test-common/utils.c, tests/test-update-install-flatpaks.c
When an OS update has flatpak(s) set to be updated or installed along
with it (via eos-updater-flatpak-installer), the flatpaks are required
for the update for succeed. So this commit adds the flatpaks to a USB
being created with eos-updater-prepare-volume so that USB updates work
even when the update in question has flatpaks to be autoinstalled. This
is accomplished by adding a "print" mode to
eos-updater-flatpak-installer and parsing the output from that in
eos-updater-prepare-volume. This way the logic that parses the
configuration files can stay in one place. Since we can't make any
assumptions about the OS version on the client receiving the USB update,
every flatpak configured to be automatically updated or installed on
OS update must be included. …
=> Add autoinstall flatpaks to update USBs

eos-updater-prepare-volume/eos-updater-prepare-volume
The `ostree create-usb` command requires an updated summary file to
function properly; see its man page.
https://phabricator.endlessm.com/T22895
=> eupv: Update the summary file before calling create-usb

test-common/utils.c
Currently the ARM OBS build is failing with the message:
(process:24961): WARNING **: Failed to load shared library
'libeos-updater-util-0.so.0' referenced by the typelib:
libeos-updater-util-0.so.0: cannot open shared object file: No such file
or directory
This commit adds the libeos-updater-util to LD_LIBRARY_PATH so that the
built .so file can be found when running the tests.
https://phabricator.endlessm.com/T21756
=> test-common: Set LD_LIBRARY_PATH when running e-u-p-v

debian/control
The eos-updater-prepare-volume script now depends on the GObject
introspection bindings for eos-updater, so add a dependency on
gir1.2-eos-updater-0 to the eos-updater-tools package, so the bindings
will be installed into Endless.
https://phabricator.endlessm.com/T22895
=> debian/control: Add eos-updater gir dep for e-u-p-v

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
The systemd service sandboxing for the boot-time Flatpak installer prevents the
Flatpak triggers from working correctly, because they are executed via bwrap.
One easily visible consequence is that the mime cache in the flatpak
export/share/applications folder is not updated, meaning that documents are not
associated with a newly-installed LibreOffice until an unrelated (and
unconstrained) Flatpak operation happens to re-run the triggers. Add the (sadly
quite broad) permissions necessary to allow bwrap to work correctly.
https://phabricator.endlessm.com/T22900
=> eos-updater-flatpak-installer.service: loosen sandboxing for bwrap

test-common/flatpak-spawn.c
Recent verisons of flatpak prompt the user for confirmation during
install/update/uninstall operations. So when the eos-updater unit tests
try to install the test runtime, there's an "Is this ok? [y/n]:"
prompt, and no is assumed since there's no user input, which eventually
leads to a unit test failure.
So this commit adds the --asumeyes option when the tests call out to
`flatpak install` or `flatpak uninstall`, which is meant for the purpose
of scripting and answers yes to questions (or the default option if it's
multiple choice).
https://phabricator.endlessm.com/T23138
=> test-common: Use the flatpak --asumeyes option

eos-updater-prepare-volume/eos-updater-prepare-volume
Now that we have a `flatpak create-usb` tool that takes care of copying
flatpaks to USBs along with their dependencies, related refs, repo
metadata, etc. there's no reason for eos-updater-prepare-volume to try
to emulate that work. So this commit changes the syntax accepted by
e-u-p-v so that it's just flatpak refs (flatpak will figure out the
collection IDs on its own) and calls out to `flatpak create-usb` after
using `ostree create-usb` to copy the OS ref.
https://phabricator.endlessm.com/T23118
=> eupv: Port to using flatpak create-usb

eos-updater-flatpak-installer/docs/eos-updater-flatpak-installer.8
The /var/lib/... directory is mentioned twice and /etc/ is left out.
=> eufi: Fix a mistake in the docs

eos-updater-prepare-volume/eos-updater-prepare-volume
Currently eos-updater-prepare-volume looks at the flatpak autoinstall
lists and simply includes all the ones that are set to be installed or
updated and none of the ones set to be uninstalled. But some apps such
as com.endlessm.CompanionAppService//eos3 have an install action and a
later uninstall action. So currently eos-updater-prepare-volume tries to
include that app on a USB, which fails since it's not installed. So this
commit fixes e-u-p-v so that for each uninstall action, it removes any
previous install/update actions in the set with the same ID.
https://phabricator.endlessm.com/T21756
=> eupv: Exclude apps that are installed then uninstalled

libeos-updater-util/flatpak.c
This commit fixes the gtk-doc annotation on the new function
euu_flattened_flatpak_ref_actions_from_paths() so it gets the
element-type correct and specifies (transfer container) instead of
(transfer full). With transfer full, the elements are freed too many
times, because Python tries to free them after freeing the pointer array
(which itself frees them).
This prevents a seg fault when running eos-updater-prepare-volume.
https://phabricator.endlessm.com/T21756
=> libeuu: Fix a gtk-doc annotation

eos-updater/eos-updater.service.in
Our benchmarks show this significantly reduces the interactivity impact of
ongoing ostree operations while the user is continuing other tasks on the
system. The effect is very pronounced with the default CFQ scheduler, and in
combination with BFQ, using the idle class improves the worst case to nearly
the same as an unloaded system.
https://phabricator.endlessm.com/T22479
=> eos-updater: set IO class to idle

eos-updater/eos-updater.conf
This commit changes the default eos-updater.conf so that eos-updater
checks USB drives (technically mounted filesystems) for OS updates in
addition to checking the Internet. The USB OS update feature seems to be
in fairly good shape and it's slated for release in 3.4.8. Previously
we've been using a hook in the image builder to change eos-updater.conf
for testing LAN/USB updates, but now that we're ready to deploy them it
makes sense to make the change here.
This commit alone doesn't enable USB OS updates. The other requirement
is for the `eos` remote to have a collection ID configured on it, which
we will be doing in the image builder for non-OEM images (and eventually
for all images and in an update for existing users as well).
https://phabricator.endlessm.com/T23413
=> eos-updater.conf: Check USB drives for updates

eos-updater-prepare-volume/eos-updater-prepare-volume
Generating the summary requires acquiring an exclusive lock on the
OSTree repository which risks this process failing if another process,
like `ostree commit` or `ostree prune`, holds an exclusive lock for
longer than OSTree's core.lock-timeout-secs config option (which
defaults to only 30 seconds which is not always sufficient).
In testing directly and with Gnome Software calling this script to copy
the OS and dependencies to USB, this step seems to be unnecessary, so
we're best off skipping it.
https://phabricator.endlessm.com/T23422
=> eupv: don't manually generate the summary

eos-updater/data.h, eos-updater/fetch.c, eos-updater/poll-common.c, eos-updater/poll-common.h, eos-updater/poll.c
Currently eos-updater asks the download scheduler (mogwai) before
fetching an update, so that the user's configured update schedule can be
respected. However that system is designed to help users with limited
Internet connections; it doesn't make sense to use it when the update
comes from local sources, such as the local network or a USB drive. So
this commit makes changes to eos-updater so that offline OS updates can
happen regardless of whether or not automatic updates are turned on.
The way this is implemented is that in the Poll() stage, we first check
offline sources for updates, and then only check the Internet if none
were found offline. If we simply check all the sources at once as we
previously were, you'd have to make significant changes to the Fetch()
stage, because the …
=> eos-updater: Avoid scheduler for offline updates

eos-updater-prepare-volume/docs/eos-updater-prepare-volume.8
Commit e4114d88 changed the format of the command line arguments
accepted by eos-updater-prepare-volume. Change its man page to
reflect that.
https://phabricator.endlessm.com/T22822
=> eos-updater-prepare-volume: Update man page to fix an error

eos-updater/apply.c
There’s no task for this one. Minor and inconsequential fix which doesn’t need backporting.
As spotted in logs https://phabricator.endlessm.com/F25729 and https://phabricator.endlessm.com/F25730.
=> Remove a pointless message spotted by Rob

eos-updater-prepare-volume/eos-updater-prepare-volume
Currently eos-updater-prepare-volume uses the collection ID from the
remote config when deciding how to specify the OS ref to `ostree
create-usb`. However this is not always accurate since for example an
image built using a staging ostree (com.endlessm.Dev.Os) will still have the production URL
and collection ID configured for updates (com.endlessm.Os). So this
commit changes e-u-p-v to use the collection ID from the commit metadata
instead, which is always the correct one.
When I wrote this I thought it wouldn't matter because I thought `ostree
create-usb` uses the collection ID from the local repo summary file,
which would still be the wrong one. However I later found out (thanks to
Dan) that the local repo summary is not needed or used for pulls between
local repos (in this case from …
=> eupv: Use collection ID from commit metadata

debian/eos-updater-tests.install, debian/eos-updater.install, debian/libeos-updater-flatpak-installer-0-tests.install, debian/libeos-updater-util-0-tests.install
Following such illustrious guidance as:
* https://salsa.debian.org/debian/flatpak-builder/commit/d525fb2f3024db21e9169605e4ab30e3cc203523
* https://manpages.debian.org/unstable/debhelper/debhelper.7.en.html
(v12 compatibility)
https://phabricator.endlessm.com/T26056
=> debian: Use libexecdir as /usr/libexec as allowed by FHS 3.0

eos-updater-prepare-volume/eos-updater-prepare-volume
Currently eos-updater-prepare-volume checks the deployment's origin
refspec to decide what ref to pass to "ostree create-usb" to copy the OS
onto a USB drive. This is not always correct; for example images built
from development OSTrees will have the production ref (e.g.
os/eos/amd64/eos3a) set as the origin so that it will be used for
updates, but the booted commit will have a different associated ref
(e.g. os/eos/amd64/master). In that case the "ostree create-usb" command
will fail. So this commit changes e-u-p-v so that it checks the commit
metadata to find the list of associated refs and copies each of those. I
think it makes more sense to copy all of them than to try to determine
which will be used on the receiving computer, and the additional disk
space usage is trivial.
In other …
=> eupv: Use ref(s) from commit metadata

eos-updater-prepare-volume/eos-updater-prepare-volume
Currently if the USB drive used for USB updates uses a filesystem that
preserves Linux permissions (such as ext4) and its toplevel directory
doesn't give read and execute permission to other users, and the user ID
who owns the flash drive is different than the logged in user's ID on
the receiving computer where the drive is used, gnome-software will
crash and fail to display the apps on the USB drive. For example if I
use the shared user with user ID 1001 to format a drive ext4, copy apps
to it, and then put it in a computer logged in as the primary user with
user ID 1000, that user will be unable to open the drive or receive
updates from it.
We already do a recursive chmod on the ".ostree" directory on the drive
after the copy, so this commit just adds another chmod command before
that …
=> eupv: Work when the user ID differs on the destination computer

debian/control, libeos-updater-util/flatpak.c
libflatpak now returns FLATPAK_ERROR_REF_NOT_FOUND instead
of G_IO_ERROR_NOT_FOUND (and sometimes other errors) when a
ref can't be found either locally or in a remote. So update
some code which checks for G_IO_ERROR_NOT_FOUND.
See these commits:
https://github.com/flatpak/flatpak/commit/c0d5f1bfc8f09d5c7038422ecd948f26eaad747c
https://github.com/flatpak/flatpak/commit/c028e0dc1b7861a507c39f76c5bb582ee2150da1
https://phabricator.endlessm.com/T26678
=> libeos-updater-util: Check for new flatpak error code

Makefile.am, debian/eos-updater.install, eos-updater/eos-updater.service.in
I constantly run `eos-updater update` rather than `eos-updater-ctl
update` thanks to tab completion. There's no reason for this executable
to be in $PATH.
https://phabricator.endlessm.com/T27471
=> Move eos-updater executable to /usr/libexec

eos-autoupdater/eos-autoupdater.timer.in
This commit makes eos-autoupdater.timer potentially start 3 minutes
after boot, rather than 15 minutes after boot. Because we have
RandomizedDelaySec=30m, in practice it will start between 3 and 33
minutes after boot. The primary reason for the change is that we will
soon be shipping PAYG Endless computers, on which if the eos-paygd
daemon crashes or exits with an error code, the whole computer shuts
down after a 20 minute grace period. This poses a risk of making
computers stuck in a boot loop and never receiving an update which might
fix the problem, in case the hypothetical crash happens before
eos-updater runs. So make such a boot loop less likely by having the
updater run automatically earlier after boot.
The reason the updater currently runs 15 minutes after boot is to give
ntp a …
=> eos-autoupdater: Lower OnBootSec from 15m to 3m

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
Without this, deploying Flatpaks after a reboot fails with the following
in the journal (line-wrapped for legibility):
Attempting to install eos-apps:app/com.hack_computer.Clubhouse/x86_64/eos3
Failed to install eos-apps:app/com.hack_computer.Clubhouse/x86_64/eos3:
Could not connect: No such file or directory
eos-updater-flatpak-installer: Couldn’t apply some flatpak update actions for this boot:
Could not connect: No such file or directory
This problem does not occur if I trigger this service once the system is
fully booted.
I believe this is because deploying a Flatpak now involves a parental
controls check, which involves talking to accountsservice on the system
bus, neither of which are running at the point where this service runs.
Work around this by using the same workaround we used …
=> eos-updater-flatpak-installer: skip parental controls checks

src/eos-updater-poll.c, tests/test-update-refspec-checkpoint.c
This is a backport of #227 to the eos3.3 branch for the purpose of QA. See the discussion in the ticket.
https://phabricator.endlessm.com/T23385
=> T23385 backport to eos3.3

eos-updater-flatpak-installer/docs/eos-updater-flatpak-autoinstall.d.5
Fix a few problems with the example JSON:
- The collection-id and remote fields are both required for install
actions.
- The collection-id field is not allowed for uninstall actions.
- The collection ID for Endless runtimes is com.endlessm.Os not
com.endlessm.Runtimes
=> eufi: Fix example JSON in docs

configure.ac, eos-updater/poll-common.c, test-common/ostree-spawn.c, tests/test-update-direct.c
OSTree upstream recently gained an API to return the parsed entries in
the `ostree.sizes` metadata[1]. Split out a helper function and use it
if it's available to sum the various commit size properies. There is one
slight behavior change here - the updater only continues on error if the
error is `G_IO_ERROR_NOT_FOUND`. This is what both APIs return when
`ostree.sizes` does not exist as well as what's now set when neither
APIs are available.
1. https://github.com/ostreedev/ostree/pull/1957
https://phabricator.endlessm.com/T18171
=> poll: Use ostree_commit_get_object_sizes if available

configure.ac, eos-updater/poll-common.c, tests/test-update-direct.c
We've backported upstream's `ostree_commit_get_object_sizes`'s to our
ostree and dropped `ostree_repo_get_commit_sizes`[1]. Drop support for
the latter since the Endless downstream ostree is the only place it
existed.
1. https://github.com/endlessm/ostree/pull/164
https://phabricator.endlessm.com/T18171
=> poll: Drop support for downstream ostree_repo_get_commit_sizes API

tests/eos-update-server.py
Since a recent debhelper compat level, libexec is `/usr/libexec` rather
than `/lib/${arch}`. The tests didn’t keep in sync with that change
(because currently these installed-only tests are only run manually).
https://phabricator.endlessm.com/T30183
=> tests: Update libexec path for eos-update-server installed tests

eos-updater-flatpak-installer/docs/eos-updater-flatpak-autoinstall.d.5, eos-updater-flatpak-installer/docs/eos-updater-flatpak-installer.8, eos-updater/com.endlessm.Updater.xml, libeos-update-server/repo.c, libeos-updater-util/avahi-service-file.h, test-common/utils.c, tests/test-update-install-flatpaks.c
Done using:
```
codespell \
--builtin clear,rare,usage \
--skip './po/*' --skip './help/*/*.po' --skip './.git/*' --skip './NEWS*' \
--write-changes .
```
and then some manual checking and editing.
=> all: Fix various typos and incorrect terminology

.flake8, eos-updater-ctl/eos-updater-ctl
Here's a diff:
```diff
State: UpdateApplied
CurrentID: '4f09a3945a3fffcaf5d9a3361b7dbc37b621d1201404a0753db874d78f0eedfb'
-    DownloadSize: int64 223547830
- DownloadedBytes: int64 223549376
+    DownloadSize: 223.5 MB (223547830 bytes)
+ DownloadedBytes: 223.5 MB (223549376 bytes)
ErrorCode: uint32 0
ErrorMessage: ''
ErrorName: ''
-FullDownloadSize: int64 1755678232
-FullUnpackedSize: int64 4088847909
+FullDownloadSize: 1.8 GB (1755678232 bytes)
+FullUnpackedSize: 4.1 GB (4088847909 bytes)
OriginalRefspec: 'eos:os/eos/amd64/master'
-    UnpackedSize: int64 452314713
+    UnpackedSize: 452.3 MB (452314713 bytes)
UpdateID: '16b7353e8e87bf05421481940152098aefa0f25a3026b8cbbcb9c01a57f0378d'
UpdateLabel: '200819-063538'
UpdateMessage: 'Built with eos-ostree-builder Release_3.8.5'
```
=> ctl: Pretty-print sizes

eos-updater-avahi/eos-updater-avahi.c, eos-updater/fetch.c, eos-updater/main.c, libeos-update-server/repo.c, libeos-updater-flatpak-installer/tests/installer.c, libeos-updater-util/flatpak-util.c
Turns out that the `operation-error` signal needs to be handled in order for transactions to behave as you’d expect them to (for example, not failing on skipped operations, returning the error code from a failed operation).
See the individual commit messages for details.
This branch should improve our error reporting from EUFI. It may fix the upgrade-time installation of Totem, but I haven’t explicitly tested that (yet).
https://phabricator.endlessm.com/T25765
=> T25765 Fix transaction operation error handling in eufi

debian/control, debian/rules
`dh_missing` now defaults to `--fail-missing`, so we can drop our
override there.
https://phabricator.endlessm.com/T25765
=> debian: Bump to debhelper-compat level 13

eos-updater-flatpak-installer/main.c, eos-updater-flatpak-installer/meson.build, eos-updater/object.c, eos-updater/poll-common.c, libeos-updater-util/meson.build, libeos-updater-util/metrics-private.h, test-common/utils.c
Report a metric when `eos-updater` or `eos-updater-flatpak-installer` fails.
Azafea changes in https://github.com/endlessm/azafea/pull/123.
https://phabricator.endlessm.com/T29247
=> T29247 Add failure metric reporting

eos-updater-prepare-volume/eos-updater-prepare-volume
In a perfect world, USB drives created with eos-updater-prepare-volume
could be used to update Endless computers on any previous OS versions,
but alas, this is not a perfect world. One of the reasons we can't keep
that promise is checkpoints ("eos.checkpoint-target"), but we also can't
guarantee we'll have all the flatpaks needed by
eos-updater-flatpak-installer on the target machine receiving the
update. This is because flatpaks may be uninstalled by the user after
being auto-installed, or they may be installed and later uninstalled by
eos-updater-flatpak-installer, as will be the case for
com.hack_computer.ProjectLibrary in 3.9.1.
So make failures of the `flatpak create-usb` command non-fatal for
flatpaks not explicitly specified by the user. We may also want to
install any missing …
=> eupv: Don't error out on missing flatpaks

debian/eos-updater.install, debian/rules, eos-updater-flatpak-installer/docs/eos-updater-flatpak-installer.8, eos-updater-flatpak-installer/eos-updater-flatpak-installer-fallback.service.in, eos-updater-flatpak-installer/eos-updater-flatpak-installer-fallback.timer.in, eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in, eos-updater-flatpak-installer/main.c, eos-updater-flatpak-installer/meson.build
This service will be run once a day during normal system use (not just
during the first boot after an upgrade, as e-u-f-i is normally run),
just in case there were errors in downloading or installing the updates
during the most recent system upgrade.
The fallback runs e-u-f-i with `--pull`, so it will download flatpaks,
runtimes, etc. if necessary. For this reason it needs to be slightly
less constrained in its systemd sandbox than
`eos-updater-flatpak-installer.service`. Other than that the service
files are almost identical.
This could be considered a hack, but could also be considered as a
safety fallback in case of mistakes in previous OS versions. Otherwise,
the e-u-f-i process is only run with the eos-updater/OSTree/flatpak code
from release X just after upgrading to release X, or …
=> T31190 eos-updater-flatpak-installer: Add a fallback service and timer

eos-updater-flatpak-installer/eos-updater-flatpak-installer-fallback.service.in
Quoth systemd.timer(5):
> […] services with RemainAfterExit= set […] are usually not suitable
> for activation via repetitive timers, as they will only be activated
> once, and then stay around forever.
And indeed before this patch,
eos-updater-flatpak-installer-fallback.timer would only fire once
(assuming the .service succeeds) because the .service is considered to
be still running after it exits.
https://phabricator.endlessm.com/T31564
=> e-u-f-i: Unset RemainAfterExit on -fallback.service

test-common/meson.build, test-common/ostree-spawn.c
The `trivial-httpd` builtin for the `ostree` command has been deprecated
for a couple years and is not included on default builds of ostree. On
the other hand, the standalone `ostree-trivial-httpd` has been available
since ostree 2017.1 in `<libexecdir>/libostree/ostree-trivial-httpd`.
Try to use that instead of the builtin.
https://phabricator.endlessm.com/T31384
=> test-common: Use standalone ostree-trivial-httpd

eos-updater/poll-common.c, test-common/utils.c, test-common/utils.h, tests/test-update-refspec-checkpoint.c
See the commit messages.
This adds a load of checks for systems which should not be migrated to `eos4`. The checks are based on searching around tasks and code for ways to distinguish these systems, rather than actual testing on these systems. The basis for the checks still needs to be checked against the actual systems.
https://phabricator.endlessm.com/T31918
=> T31918 Teach eos-updater not to cross eos3a→eos4 checkpoint on certain systems

eos-updater-flatpak-installer/eos-updater-flatpak-installer-fallback.service.in, eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
Split disk support has been dropped for EOS 4 and the
eos-extra-settled.target unit is no longer installed. Don't require or
wait for it when installing flatpaks.
https://phabricator.endlessm.com/T32298
=> flatpak-installer: Drop dependency on eos-extra-settled.target

eos-updater-ctl/eos-updater-ctl
Spotted on GNOME OS:
======= Properties =======
State: Fetching
CurrentID: 'fc691d2fdcd5f7d44062a301888d1a86f00f48d803d1c3278915b4460e70a617'
Traceback (most recent call last):
File "/usr/bin/eos-updater-ctl", line 124, in name_appeared_cb
dump_daemon_properties(proxy)
File "/usr/bin/eos-updater-ctl", line 94, in dump_daemon_properties
value = GLib.format_size_full(
OverflowError: -1 not in range 0 to 18446744073709551615
This is because on GNOME OS the necessary OSTree metadata is not
available to tell eos-updater the download size and unpacked size, only
the number of bytes that have been downloaded so far:
[gnome@linux ~]$ gdbus introspect --system --dest com.endlessm.Updater --object-path /com/endlessm/Updater --only-properties
node /com/endlessm/Updater {
interface …
=> ctl: Handle size properties being negative

eos-updater/poll-common.c, test-common/utils.c, test-common/utils.h, tests/test-update-refspec-checkpoint.c
These are the 3 commits representing the conditional checkpoint implementation and tests. On my local machine none of the flatpak fixes were needed since 3.9 is still using flatpak 1.8. We'll see if Jenkins agrees.
https://phabricator.endlessm.com/T32162
=> Backport eos3a → eos4 conditional checkpoint work

eos-updater/poll-common.c, tests/test-update-refspec-checkpoint.c
The eos3a → eos4 checkpoint tests were only being applied when the refs
were literally `eos3a` and `eos4`. Unfortunately, our refs actually look
like `os/eos/<arch>/<branch>`. Expand the matches so they also accept
`/<branch>` at the end of the ref.
https://phabricator.endlessm.com/T32162
=> eos-updater: Fix ref matching for eos3a → eos4 checkpoint tests

tests/test-update-refspec-checkpoint.c
When the test host is `aarch64`, the expected results of these tests are
effectively ignored unless architecture itself is being mocked. See
17e9b623bac9af8fd34eb593cc238a89327ea9c4 for details.
This caused a problem for the ref matching tests when run on `aarch64`.
These cases set a condition that would cause the checkpoint to be
ignored and then use different refs to check if the condition is
actually used. When the host arch is `aarch64`, the test later decides
that the expected result is an ignored checkpoint regardless of what the
test case said the expected result is.
To workaround this, change the ref matching cases to override the
architecture to `aarch64`. This prepares the checkpoint to be ignored
when the refs match as it was previously using the split disk override
for. …
=> eos-updater: Mock architecture for eos3a → eos4 ref matching tests

eos-updater/meson.build, libeos-update-server/meson.build, test-common/meson.build
it is invalid and fails to build with meson 0.60
=> build: remove 'version' parameter from static libraries

debian/control, debian/eos-updater.install, eos-updater/apply.c, eos-updater/eos-updater-autocleanup.service.in, eos-updater/finalize-autocleanup.conf.in, eos-updater/meson.build, tests/meson.build
When finalizing an OSTree deployment, the current `/etc` is merged with
the new commit's `/usr/etc`. Any changes that happen in the current
`/etc` after the deployment has been finalized will not appear in the
new deployment. Since eos-updater is often run in the background, it's
likely the user will make changes in `/etc` (such as creating a new
user) long before the new deployment is booted into.
To address this issue, OSTree has provided the concept of a staged
deployment since 2018.5. The new deployment is initialized but not
finalized during shutdown via the `ostree-finalize-staged.service`
systemd unit. Since staged deployments only work on OSTree booted
systems that can initiate systemd units, this can't really work in the
current test suite. The old full deployment method is kept …
=> apply: Use staged deployment on booted systems

libeos-updater-util/types.c
It is not needed per the g_dbus_error_register_error_domain() docs.
=> Don't use volatile qualifier for quark

eos-updater/apply.c
This reverts commit 12d263bfd3ee9e1e44a8d3704088edd038fd8883. On systems
such as PAYG where `/boot` is an automount,
`ostree-finalize-staged.service` fails to work correctly if the
automount expires before shutdown. Until a solution to that issue is
found, go back to the non-staged deployments we've used for years.
https://phabricator.endlessm.com/T5658
https://github.com/systemd/systemd/issues/22528
https://github.com/ostreedev/ostree/issues/2543
=> Revert "apply: Use staged deployment on booted systems"

debian/control, eos-updater/apply.c, libeos-updater-util/meson.build, libeos-updater-util/ostree-util.c, libeos-updater-util/ostree-util.h, libeos-updater-util/tests/ostree-util.c
Bring back staged deployments for eos4.0 with the workaround to not use them on an automounted `/boot`.
https://phabricator.endlessm.com/T33136
=> Restore staged deployments for eos4.0

eos-updater-flatpak-installer/docs/eos-updater-flatpak-autoinstall.d.5
This has been true since the very first commit of this functionality,
but was previously undocumented except in a source-code comment.
=> Document that an empty autoinstall file is legal

eos-updater/poll-common.c, tests/test-update-refspec-checkpoint.c
Block Weibu F3C (Endless EE-200) updates to EOS 5 from EOS 4. It is not
on the EOS 5 support list. Add corresponding tests as well.
https://phabricator.endlessm.com/T33311
=> eos-updater: Block Weibu F3C updates to EOS 5 from EOS 4

debian/control, eos-updater/apply.c, libeos-updater-util/meson.build, libeos-updater-util/ostree-util.c, libeos-updater-util/ostree-util.h, libeos-updater-util/tests/ostree-util.c
This reverts commit a19821a2b419850e188da3eee4fe3465528ca920. OSTree has been fixed to support this use case by keeping `/boot` open in the root namespace until the staged deployment completes finalization. See https://github.com/ostreedev/ostree/pull/2544 for details.
https://phabricator.endlessm.com/T33775
=> Revert "apply: Don't use staged deployments when /boot is automounted"

eos-updater/poll-common.c, tests/test-update-refspec-checkpoint.c
Block ECS EF20EA (Standard EF20EA) updates to EOS 5 from EOS 4. It is not
on the EOS 5 support list. Add corresponding tests as well.
https://phabricator.endlessm.com/T33759
=> eos-updater: Block ECS EF20EA updates to EOS 5 from EOS 4

tests/test-update-refspec-checkpoint.c
The host_is_aarch64 flag guards the update from eos4 to eos5 for the aarch64 platforms. It disabled the updating on aarch64 platforms originally. This commit lets aarch64 follow the normal updating check from eos4 to eos5.
https://phabricator.endlessm.com/T33759
=> eos-updater: Let aarch64 follow the normal eos4 -> eos5 update procedure

.flake8, eos-updater-prepare-volume/eos-updater-prepare-volume, tests/eos-updater-avahi.py
I went to run the test suite and my more recent version of `flake8` didn't like `eos-updater-prepare-volume`. Then I decided to get the whole project spruced up.
=> Polish flake8 setup

eos-update-server/meson.build, eos-updater-avahi/meson.build, eos-updater-flatpak-installer/meson.build, eos-updater/meson.build, eos-updater/poll-common.c, libeos-update-server/meson.build, libeos-updater-flatpak-installer/meson.build, libeos-updater-flatpak-installer/tests/meson.build, libeos-updater-util/meson.build, libeos-updater-util/tests/meson.build, test-common/convenience.c, test-common/flatpak-spawn.c, test-common/flatpak-spawn.h, test-common/meson.build, test-common/ostree-spawn.c, test-common/ostree-spawn.h, test-common/utils.c, test-common/utils.h, tests/meson.build, tests/test-update-direct.c, tests/test-update-from-lan.c, tests/test-update-from-main.c, tests/test-update-from-volume.c, tests/test-update-refspec-checkpoint.c, tests/test-update-refspec-endoflife.c
This adds checkpoints to:
* Confirm `/var/lib/flatpak/repo` has been split from `/ostree/repo`
* Confirm that the `sysroot.bootloader` option is set in the `/ostree/repo` config
before allowing upgrade from eos4 → eos5.
Both of the actual checks were pretty simple. I ended up spending much more time mucking with the test suite. Probably some of that can be split out to a separate PR if desired.
https://phabricator.endlessm.com/T34110
=> More eos4 → eos5 checkpoints

tests/meson.build
This runs `reuse lint` if it’s installed. I’m not adding it as a dependency to `debian/control` at the moment as it’s not packaged on Bullseye. So for the moment this test will only be run locally by developers.
=> tests: Add licensing compliance test

test-common/utils.c
I noticed this while putting together backports for eos4.0.
https://phabricator.endlessm.com/T34110
=> tests: Fix leaks in flatpak repo setup

eos-updater/meson.build, eos-updater/tests/eos_updater.py, eos-updater/tests/meson.build, meson.build
This is a mock implementation of eos-updater written using
python-dbusmock. It’s distributed by default, but not used by anything
at the moment; eventually some automated tests for eos-updater clients
could be written with it (using python-unittest), but for the moment
it’s only being used manually (using `python3 -m dbusmock --template
./path/to/mock-eos-updater.py`).
https://phabricator.endlessm.com/T26011
=> tests: Add mock eos-updater service

eos-updater/com.endlessm.Updater.xml, eos-updater/main.c, eos-updater/poll-common.c, eos-updater/poll-common.h, eos-updater/poll.c, test-common/utils.c, tests/test-update-direct.c, tests/test-update-refspec-checkpoint.c
See the commit messages for explanations.
https://phabricator.endlessm.com/T34079
=> eos-updater: Add a new UpdateIsUserVisible D-Bus property and implicitly set it if the major version in an update differs from what’s booted

eos-update-server/meson.build, eos-updater-avahi/meson.build, eos-updater-flatpak-installer/meson.build, eos-updater/meson.build, eos-updater/poll-common.c, libeos-update-server/meson.build, libeos-updater-flatpak-installer/meson.build, libeos-updater-flatpak-installer/tests/meson.build, libeos-updater-util/meson.build, libeos-updater-util/tests/meson.build, test-common/convenience.c, test-common/flatpak-spawn.c, test-common/flatpak-spawn.h, test-common/meson.build, test-common/ostree-spawn.c, test-common/ostree-spawn.h, test-common/utils.c, test-common/utils.h, tests/meson.build, tests/test-update-direct.c, tests/test-update-from-lan.c, tests/test-update-from-main.c, tests/test-update-from-volume.c, tests/test-update-refspec-checkpoint.c, tests/test-update-refspec-endoflife.c
This cherry picks #311 and #314 for eos4.0. See those PRs for details. Possibly a couple of the commits aren't needed, but it didn't seem worth the effort to tease the important changes out. The only conflict was in `libeos-updater-util/meson.build` since it still has the libmount dependency that was dropped in master.
https://phabricator.endlessm.com/T34110
=> Repo checkpoint eos4.0 backports

eos-updater/tests/eos_updater.py
We don’t currently use this for testing, but it’s good to keep the template up to date with the actual D-Bus interface.
https://phabricator.endlessm.com/T34079
=> tests: Add UpdateIsUserVisible support to the mock eos-updater template

eos-updater/com.endlessm.Updater.xml, eos-updater/main.c, eos-updater/poll-common.c, eos-updater/poll-common.h, eos-updater/poll.c, test-common/utils.c, tests/test-update-direct.c, tests/test-update-refspec-checkpoint.c
This is a backport of #312 to eos4.0 to allow showing release details for the eos5.0 upgrade.
https://phabricator.endlessm.com/T34160
=> Backport UpdateIsUserVisible property to eos4.0

tests/test-update-refspec-checkpoint.c
We only need one of these tests with one or more known negative conditions to check that eos-updater honors the
`EOS_UPDATER_FORCE_FOLLOW_CHECKPOINT` environment variable. This is a slow test, so any redundant cases should be dropped.
=> tests: Reduce EOS_UPDATER_FORCE_FOLLOW_CHECKPOINT tests

eos-updater/com.endlessm.Updater.xml, eos-updater/docs/eos-updater.8, eos-updater/main.c, eos-updater/poll-common.c, eos-updater/poll-common.h, eos-updater/poll.c, eos-updater/tests/eos_updater.py, tests/test-update-direct.c
This adds a `ReleaseNotesUri` property to the D-Bus interface. This is populated from an optional `eos-updater.release-notes-uri` metadata key in OSTree commits, which has a couple of optional string substitutions applied to it to allow a single URI template to be refined for multiple possible update paths.
This allows different release notes pages to be shown to users depending on which version they are updating from.
Includes a unit test.
https://phabricator.endlessm.com/T34082
=> eos-updater: Add a ReleaseNotesUri property

test-common/utils.c, test-common/utils.h, tests/test-update-direct.c
Passing compound literals to `eos_test_add` was subtly broken due the implementation of the `g_test_add` macro. Workaround it by converting `eos_test_add` to a function and fixing a test that was silently being skipped.
=> Fix tests using compound literals

eos-updater/com.endlessm.Updater.xml, eos-updater/docs/eos-updater.8, eos-updater/main.c, eos-updater/poll-common.c, eos-updater/poll-common.h, eos-updater/poll.c, tests/test-update-direct.c
Fairly trivial backport of https://github.com/endlessm/eos-updater/pull/319 to `eos4.0`.
The only cherry-pick conflict was with the python-dbusmock template for eos-updater: it was modified in the first commit, but doesn’t exist in the `eos4.0` version of eos-updater, so I dropped those changes.
https://phabricator.endlessm.com/T34292
=> T34292 Backport “eos-updater: Add a ReleaseNotesUri property” to eos4.0

eos-updater/poll-common.c, tests/test-update-refspec-checkpoint.c
Only EOS 4 systems on the latest ref (latest1) should upgrade to EOS 5 (latest2). Systems on the LTS ref (eos4) or any other ref should not. In order to ensure that the validation applies to any ref trying to follow the latest2 checkpoint, switch the initial check so that it applies to the target ref instead of the booted ref.
https://phabricator.endlessm.com/T34298
=> eos-updater: Only allow latest2 checkpoint from latest1

eos-autoupdater/main.c, test-common/spawn-utils.c, tests/test-autoupdater.c
If eos-updater was already past the polling stage, the autoupdater was segfaulting because it wasn't loading the poll results prior to using them in the apply stage. The last commit fixes that while the first 2 are minor test fixes.
https://phabricator.endlessm.com/T34083
=> Ensure autoupdater poll results are loaded

eos-autoupdater/main.c, test-common/spawn-utils.c, tests/test-autoupdater.c
This is a backport of #326 to eos4.0. The 3 commits there cherry picked cleanly.
https://phabricator.endlessm.com/T34083
=> Backport "Ensure autoupdater poll results are loaded" to eos4.0

debian/control, debian/eos-updater-dev.install, eos-updater/tests/meson.build, meson.build
Since https://github.com/martinpitt/python-dbusmock/pull/169 (not yet released!), python-dbusmock supports loading them from `$XDG_DATA_DIRS`.
If we install the template, other projects (like gnome-software) can eventually use the installed version rather than shipping their own copy.
=> eos-updater: Install python-dbusmock template

debian/eos-updater-dev.install
=> debian: Fix typo in path in eos-updater-dev.install

debian/control, eos-update-server/meson.build, test-common/httpd.c, test-common/httpd.h, test-common/meson.build, test-common/ostree-spawn.c, test-common/ostree-spawn.h, test-common/utils.c, test-common/utils.h
This replaces the use of `ostree-trivial-httpd` with an in-process `SoupServer`. `ostree-trivial-httpd` is not really intended for public consumption and is hard to debug since it's run as a daemon with its standard streams closed. The `SoupServer` implementation doesn't have as many features, but it does have all the features eos-updater was depending on.
=> Use SoupServer for tests

libeos-updater-flatpak-installer/meson.build, meson.build, meson_options.txt
With freedesktop-sdk we build eos-updater but without tests. As part of https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1564 this submission is to allow said build mode without patches
=> Support building with no tests

debian/control
This reverts commit f99859d2ffa2a79094b79f83848f6f2575e9f8bc.
When built on OBS, `reuse lint` complains at great length about build artifacts not containing copyright and licensing information:
The following files have no copyright and licensing information:
* /usr/src/packages/BUILD/obj-x86_64-linux-gnu/.gitignore
* /usr/src/packages/BUILD/obj-x86_64-linux-gnu/.hgignore
[ … ]
* /usr/src/packages/BUILD/obj-x86_64-linux-gnu/eos-autoupdater/eos-autoupdater.p/main.c.o
[ … ]
All the allegedly-offending files are in
/usr/src/packages/BUILD/obj-x86_64-linux-gnu. We can see above that Meson has written a blanket .gitignore and .hgignore to that directory as normal, so why is reuse complaining? The answer seems to be that reuse does not read these files directly. Instead, it uses the `git` (or …
=> Revert "debian: Build-depend on 'reuse'"

eos-updater/poll-common.c
The logic in the tests that used this
EOS_UPDATER_TEST_UPDATER_CUSTOM_DESCRIPTORS_PATH environment variable was removed in 019eb5971e75f3ec2087758822e9ea0a3c233586.
https://phabricator.endlessm.com/T35247
=> Remove support for overriding hardware descriptors

eos-updater/poll-common.c, eos-updater/poll.c
The `vendor` & `product` case was noticed by @dbnicholson on another PR. As described in the commit message and in that comment that I have now lost, I don't think this is a correctness issue, but it is a good-practice and readability issue.
I then searched the source tree for other lines containing the string `g_auto` and not the string `=`, and found a couple more cases. One of them is actually wrong, but only in an error path that will never be reached in practice.
https://phabricator.endlessm.com/T35247
=> Initialise g_auto* variables
