debian/eos-updater.postinst
debian/rules

Handle systemd units better

---

src/eos-updater-poll.c

Report no updates are available if the "new" version doesn't
have a newer timestamp than the currently booted version.
This matches the behavior of "ostree admin upgrade", except
having an older version available isn't reported as an error.
If a downgrade is needed for testing,
"ostree admin upgrade --allow-downgrade" can be used.
[endlessm/eos-shell#2586]

Disallow downgrades

---

README.md
configure.ac
src/eos-updater-apply.c
src/eos-updater-poll.c
src/eos-updater-util.c
src/eos-updater.xml

Select OSTree branch at run-time based on product model

---

src/eos-updater-data.c
src/eos-updater-util.c

https://phabricator.endlessm.com/T12107

Fix some dumb mistakes

---

src/eos-updater-ctl

https://phabricator.endlessm.com/T12364

eos-updater-ctl: convert to python3

---

debian/control

https://phabricator.endlessm.com/T12364-debian

Adjust dependencies

---

configure.ac
debian/control

https://phabricator.endlessm.com/T14894#336250

T14894 build fixes

---

src/eos-autoupdater.c

Connecting to NetworkManager means connecting to the system bus, which
we might not have permission to do when running in unit tests. This
could cause construction of the NmClient to fail, which would take us
down with it.
Instead, don’t connect to NetworkManager when running the unit tests
(which use a mock session bus). Ideally we’d fix this by using a mock
system bus when running the tests, but GTestDBus doesn’t support that
(and adding support for it is not going to be accepted upstream: see bug
a fake bus instance (outside process) instead, but that’s work for
later.
https://phabricator.endlessm.com/T14894
---
https://phabricator.endlessm.com/T14894#336274

eos-autoupdater: Don’t connect to NetworkManager in tests

---

libeos-updater-util/tests/avahi-service-file.c

Jenkins runs as root or some other user with CAP_DAC_OVERRIDE, which
foils our attempts to simulate unwriteable directories. This causes
spurious test failures on Jenkins (and nowhere else). Since the tests
are going to be run often enough during development, we can just skip
them on Jenkins.
https://phabricator.endlessm.com/T15544

tests: Skip permissions-based Avahi .service file tests on Jenkins

---

tests/eos-test-utils.c

Fix the integration test for `eos-update-server`.
https://phabricator.endlessm.com/T15544

T15544 update server tests

---

src/eos-updater-policy.xslt

https://phabricator.endlessm.com/T15794

T15794 fix dbus policy

---

data/docs/eos-updater.conf.5
data/eos-update-server.socket.in
eos-updater-avahi/eos-updater-avahi.service.in
src/docs/eos-autoupdater.8
src/eos-autoupdater.c
src/eos-updater-poll-volume-dbus.c
src/eos-updater.c
tests/eos-updater-avahi.py

https://phabricator.endlessm.com/T15870

T15870 fixes

---

src/eos-repo-server.c

When sending OSTree blobs over the network, we compress them on the fly
to convert from bare format into archive-z2 format. Previously, we were
using the default compression level which, for our version of OSTree, is
9 — the highest zlib compression level.
This results in a lot of CPU usage, which is not good when multiple
clients are simultaneously downloading from this computer. It makes
eos-update-server consume all of the available CPU.
Instead of compression level 9, use compression level 2. This requires a
third of the CPU time, giving compression which is about 90% as good as
level 9. It’s worth noting that upstream OSTree has since switched to
level 6 by default.
This depends on a new API in OSTree,
ostree_raw_file_to_archive_z2_stream_with_options(), which will be
available in …

eos-repo-server: Set compression level to 2 rather than 9

---

src/eos-repo-server.c

https://phabricator.endlessm.com/T15953

T15953 summary bootstrap

---

src/eos-updater-avahi.c

Previously, the code was assuming that service resolution always
succeeds, but that’s not the case. If it fails, the address is returned
as NULL.
See the example code:
http://www.avahi.org/doxygen/html/client-browse-services_8c-example.html#a21
https://phabricator.endlessm.com/T15948

eos-updater-avahi: Correctly handle service resolution failure

---

data/eos-autoupdater.timer.in

https://phabricator.endlessm.com/T15977

Disable eos-autoupdater.timer based on cmdline

---

data/docs/eos-autoupdater.conf.5
data/eos-autoupdater.conf
src/eos-autoupdater.c
tests/eos-test-utils.c

https://phabricator.endlessm.com/T15975

T15975 autoupdater jitter

---

src/docs/eos-updater-ctl.8
src/eos-updater-ctl

https://phabricator.endlessm.com/T15999

T15999 eos updater ctl enable server

---

src/eos-updater-avahi.c

https://phabricator.endlessm.com/T16095

T16095 avahi caching

---

data/eos-autoupdater.service.in
data/eos-autoupdater.timer.in
data/eos-update-server.service.in
data/eos-update-server.socket.in
data/eos-updater.service.in

https://phabricator.endlessm.com/T16103

T16103 unit cycle

---

src/eos-repo-server.c

Previously they were reset only on successful requests, meaning that a
long-running timed out request in the middle of a legitimate stream of
update requests from a client would cause eos-update-server to exit.
https://phabricator.endlessm.com/T16270

eos-repo-server: Reset timeout conditions on failed requests

---

src/eos-updater-avahi.c

Avahi doesn’t do this for us, and a link-local IPv6 address is useless
without a scope ID (since the same address can be used for multiple
machines on different interfaces; the scope ID disambiguates the
interface).
This fixes failures to poll and pull from LAN peers over IPv6 with the
error message “Failed to fetch latest commit from …: Could not connect:
Invalid argument”.
https://phabricator.endlessm.com/T16385

eos-updater-avahi: Include scope ID in link-local IPv6 addresses

---

eos-updater-avahi/docs/eos-updater-avahi.8

Add some information about IGMP problems on the eos-updater-avahi man
page, and advise people to look at their router configurations if they
encounter symptoms like this.
https://phabricator.endlessm.com/T16013

docs: Mention mDNS/IGMP problems in eos-updater-avahi man page

---

src/docs/eos-update-server.8
src/eos-repo-server.c
src/eos-update-server.c

https://phabricator.endlessm.com/T16387

T16387 connection terminated unexpectedly

---

tests/eos-test-utils.c
tests/spawn-utils.c

Just some minor fixes I have made during checking the hangs in the LAN update tests.

Test log fixes

---

Makefile.am
configure.ac
libeos-updater-util/util.h
src/Makefile.am
src/eos-autoupdater.c
src/eos-update-server.c
src/eos-updater-apply.c
src/eos-updater-avahi.c
src/eos-updater-fetch.c
src/eos-updater-poll-common.c
src/eos-updater-poll-lan.c
src/eos-updater.c

https://phabricator.endlessm.com/T15811

Convert to structured logging

---

src/eos-autoupdater.c

Only write it if a randomised delay is configured, otherwise our first
check for updates will be delayed by the IntervalDays period. When we do
write it, discount the normal IntervalDays period so that the update
will be performed after the RandomizedDelayDays period *only*.
(Non-trivial rebase to eos3.1.)
https://phabricator.endlessm.com/T16643

eos-autoupdater: Don’t normally write stamp file on first boot

---

libeos-update-server/config.c
libeos-update-server/repo.c
libeos-updater-util/config.c
libeos-updater-util/config.h
libeos-updater-util/tests/config.c
src/eos-autoupdater.c
src/eos-updater-poll.c
tests/misc-utils.c

This includes two trivial commits to fix some compiler warnings (one potentially impactful) which I spotted while working on this.
https://phabricator.endlessm.com/T18308

euu/config: Expand config API to support per-key fallbacks

---

Makefile.am
configure.ac
libeos-update-server/config.c
libeos-update-server/libeos-update-server.gresource.xml
libeos-updater-util/config.c
libeos-updater-util/config.h
libeos-updater-util/tests/Makefile.am
libeos-updater-util/tests/config-test-invalid.conf
libeos-updater-util/tests/config-test.conf
libeos-updater-util/tests/config.c
libeos-updater-util/tests/config.gresource.xml
src/Makefile.am
src/eos-autoupdater.c
src/eos-updater-poll.c
src/eos-updater.gresource.xml
tests/eos-test-utils.c

Also improve the debug output from one of the integration tests to make this actually diagnosable in future.
Requesting review from @cosimoc and @mwleeds, but feel free to split it or delegate it amongst yourselves as per your current workloads. Thanks!
https://phabricator.endlessm.com/T18308

T18308 — fix tests to work with uninstalled config files

---

Makefile.am
configure.ac
eos-update-server/eos-update-server.c
eos-updater-avahi/docs/eos-updater-avahi.8
eos-updater-avahi/eos-updater-avahi.c
libeos-update-server/repo.c
libeos-updater-util/avahi-service-file.c
libeos-updater-util/avahi-service-file.h
libeos-updater-util/extensions.c
libeos-updater-util/extensions.h
libeos-updater-util/ostree-bloom-private.h
libeos-updater-util/ostree-bloom.c
libeos-updater-util/tests/avahi-service-file.c
tests/eos-updater-avahi.py

This is a continuation of PR #95 since I don't have write access to the branch on that one. After CR/QA, the fixup commits need to be squashed and the commit message on f3cf6b58b6c81f82b04a33de023fc0ea026b502b should be updated, then this can be merged.

new DNS-SD records (continued from #95)

---

Makefile.am
configure.ac
libeos-updater-util/ostree-bloom.c
libeos-updater-util/tests/Makefile.am
src/Makefile.am
tests/Makefile.am

A few small fixes I needed to make while doing some QA locally.

Build system fixes and improvements

---

eos-update-server/eos-update-server.c
libeos-update-server/repo.c
libeos-updater-util/avahi-service-file.c
libeos-updater-util/extensions.c
libeos-updater-util/extensions.h
libeos-updater-util/refcounted.h
libeos-updater-util/util.c
libeos-updater-util/util.h
src/eos-autoupdater.c
src/eos-prepare-usb-update.c
src/eos-updater-avahi.c
src/eos-updater-avahi.h
src/eos-updater-poll-common.h
src/eos-updater-poll-lan.c
src/eos-updater.c
tests/eos-test-utils.h
tests/spawn-utils.h

https://phabricator.endlessm.com/T19388

Fixes for compiling/analysing with Clang

---

libeos-update-server/repo.c

A couple of minor fixes for problems spotted while starting to work on https://phabricator.endlessm.com/T19367.

Fix trying to list directories in eos-update-server

---

test-common/flatpak-spawn.c
test-common/utils.c

A few leaks spotted while reviewing the next commit in https://phabricator.endlessm.com/T16682.

Fixes for leaks spotted while reviewing T16682

---

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in

Various fixes to the unit file to ensure that it runs correctly on boot.

T16682: Various fixes to the eos-updater-flatpak-installer.service unit

---

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in

Otherwise a shutdown will interrupt installation.

flatpak-installer: Add Conflicts=shutdown.target

---

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
libeos-updater-util/flatpak.c
libeos-updater-util/tests/flatpak.c
src/docs/eos-updater.8

A few small fixes for the T16682 work to ensure it does everything the [design says](https://docs.google.com/document/d/17EN0tP5dn6WYW9OfFu37oId-O4CgkVUjzSMNAay39dE/edit#).

T16682 spec compliance

---

eos-updater-flatpak-installer/eos-updater-flatpak-installer.service.in
eos-updater-flatpak-installer/main.c
libeos-updater-flatpak-installer/perform-flatpak-actions.c

Some additional fixes to T16682, particularly in permissions that seemed to be getting in the way when installing `com.endlessm.CompanionAppService`
https://phabricator.endlessm.com/T20708

T16682: Additional service file touchups

---

eos-updater-flatpak-installer/eos-updater-autoinstall.schema.json
libeos-updater-flatpak-installer/determine-flatpak-actions.c
libeos-updater-flatpak-installer/perform-flatpak-actions.c
libeos-updater-flatpak-installer/tests/installer.c
libeos-updater-util/flatpak.c
libeos-updater-util/flatpak.h
libeos-updater-util/tests/flatpak.c
src/eos-updater-fetch.c
test-common/flatpak-spawn.c
test-common/flatpak-spawn.h
test-common/utils.c
test-common/utils.h
tests/test-update-install-flatpaks.c

https://phabricator.endlessm.com/T20809

T20809: Make 'branch' specification mandatory

---

libeos-updater-flatpak-installer/tests/installer.c
test-common/flatpak-spawn.c
test-common/flatpak-spawn.h
test-common/utils.c
test-common/utils.h
tests/test-update-install-flatpaks.c

It's the test we had to have.
https://phabricator.endlessm.com/T20812

T20812: Add testcase for systems that don't yet have collection-ids

---

libeos-updater-util/util.c
libeos-updater-util/util.h
src/eos-updater-poll-common.c
src/eos-updater.c

https://phabricator.endlessm.com/T20888

T20888 Improve handling of invalid /ostree/repos

---

libeos-updater-util/tests/flatpak.c

This was accidentally nuked in #155 .
https://phabricator.endlessm.com/T20809

T20809: Restore clobbered test

---

eos-updater-flatpak-installer/docs/eos-updater-flatpak-autoinstall.d.5
libeos-updater-util/flatpak.c
libeos-updater-util/flatpak.h
libeos-updater-util/tests/flatpak.c

https://phabricator.endlessm.com/T20809

T20809: Some follow-up comments

---

libeos-updater-flatpak-installer/perform-flatpak-actions.c
src/eos-updater-fetch.c
tests/test-update-install-flatpaks.c

Arguably a design bug in Flatpak itself.
https://phabricator.endlessm.com/T20881

T20881: Ignore FLATPAK_ERROR_ALREADY_INSTALLED when updating

---

libeos-updater-util/tests/flatpak.c

https://phabricator.endlessm.com/T20876

T20876: Add test for invalid entry as "serial" number

---

src/eos-updater-fetch.c

Fetching the updates was honoring the 'download-now' property from
Mogwai's Scheduled Entry for starting, but once it started, it'd not get
canceled even if Mogwai reported download-now=false for the entry.
This patch implements that cancellation by using a local cancellable
object for the fetching operation instead of the one that's passed to
the call, since the latter should only be cancelled by the Cancel()
DBus method (in order to avoid future issues).
https://phabricator.endlessm.com/T22237

Cancel fetching when Mogwai asks it to not download

---

src/eos-updater-poll.c

As @dbnicholson spotted in https://github.com/endlessm/eos-updater/pull/195/files/e57fba023ce06b9f32524010057d2570dcc24967#r185319556
https://phabricator.endlessm.com/T22295

T22295: Fix unconditional failure in libostree P2P metadata fetch code

---

src/eos-updater-fetch.c

The fetch operation couldn't be canceled because the check_scheduler was
blocked iterating its context (while waiting for Mogwai's signals).
These changes add a new GSource from the cancellable object to the
GMainContext, so when the cancellable is canceled the main context
iterates and thus allows for the operation to stop.
https://phabricator.endlessm.com/T21133

fetch: Ensure we can cancel checking the scheduler

---

libeos-updater-util/flatpak.c
libeos-updater-util/tests/flatpak.c

https://phabricator.endlessm.com/T22054

T22054: Logging improvements

---

eos-updater-flatpak-installer/main.c
eos-updater/fetch.c
libeos-updater-flatpak-installer/installer.h
libeos-updater-flatpak-installer/perform-flatpak-actions.c
libeos-updater-util/flatpak.c
tests/test-update-install-flatpaks.c

https://phabricator.endlessm.com/T22054

T22054 Allow installing dependencies from remotes without a locally configured collection ID

---

eos-updater/poll-common.c
libeos-updater-flatpak-installer/tests/installer.c
libeos-updater-util/flatpak.c
libeos-updater-util/util.c
libeos-updater-util/util.h
test-common/convenience.c
test-common/convenience.h
test-common/misc-utils.c
test-common/misc-utils.h
test-common/utils.c
test-common/utils.h
tests/Makefile.am
tests/test-update-broken-delta.c
tests/test-update-cleanup-workaround.c
tests/test-update-direct.c
tests/test-update-from-lan.c
tests/test-update-from-main.c
tests/test-update-from-volume.c
tests/test-update-install-flatpaks.c
tests/test-update-missing-deployed-commit.c
tests/test-update-refspec-checkpoint.c

https://phabricator.endlessm.com/T22805
Rebased and ready for full review and merging.

T22805: eos-updater: Allow upgrades even if the current commit is missing

---

libeos-updater-util/flatpak.c
tests/test-update-install-flatpaks.c

Instead of erroring out completely, blocking updates, just log
a message indicating that the remote is broken and don't search
it for things like runtimes or related refs. We require things
like summary files to be present on remotes and this will be broken
the moment a user installs a flatpak bundle since those don't have
summaries generated on their remote configuration.
https://phabricator.endlessm.com/T23347

flatpak: Don't search broken remotes for dependencies

---

eos-updater/poll.c
tests/test-update-refspec-checkpoint.c

https://phabricator.endlessm.com/T23385

T23385: Drop old refspec and prune after following checkpoint

---

eos-updater/apply.c
tests/test-update-from-main.c

This commit makes eos-updater add a collection ID to the OS remote
config during the apply stage, in a similar way that the "branches"
config key is currently added. This has the effect of enabling LAN/USB
OS updates when the eos-updater config file has those sources enabled.
After the next checkpoint this patch can be dropped, because at that
point every user's config will have been updated.
https://phabricator.endlessm.com/T19363

apply: Add a collection ID to the OS remote config

---

eos-updater-prepare-volume/docs/eos-updater-prepare-volume.8
eos-updater-prepare-volume/eos-updater-prepare-volume

https://phabricator.endlessm.com/T25940

Add a --preserve-permissions option for e-u-p-v

---

Makefile.am
test-common/utils.c
tests/services/org.freedesktop.Flatpak.SystemHelper.service.in

https://phabricator.endlessm.com/T26806

T26806 Fix tests running locally

---

eos-updater-flatpak-installer/meson.build
eos-updater/meson.build
eos-updater/object.c
meson.build

https://phabricator.endlessm.com/T29247

T29247 Metrics fix

---

tests/test-update-install-flatpaks.c

With newer flatpak, an indexed summary file will be created on the
server and the client will try to download `summary.idx` first. This
breaks the test that expects to fail when there's no collection ID in
the remote summary since flatpak only validates its presence on a full
`summary` file.
Since the Endless servers aren't providing indexed summaries yet, it's
useful to continue simulating this test with a full summary that doesn't
contain a collection ID. If the summary index exists, delete it to go
back to older flatpak behavior.
https://phabricator.endlessm.com/T31918

tests: Remove indexed summary for invalid collection ID test

---

tests/test-update-refspec-checkpoint.c

Since the checkpoint redirect should not be followed on aarch64 hosts,
the tests are going to behave slightly differently on that architecture:
we should expect the checkpoint to never be followed unless the
architecture is mocked, or following redirects is forced.
The alternative approach would be to always mock the architecture, and
set it to something other than aarch64 (unless explicitly testing the
architecture checks), but then we’d be throwing away an opportunity to
test the checkpoint code on exactly the platform it’s meant to catch.
https://phabricator.endlessm.com/T31918

eos-updater: Tweak eos3a → eos4 checkpoint tests on aarch64 hosts

---

libeos-updater-util/flatpak-util.c
libeos-updater-util/tests/flatpak-util.c
test-common/ostree-spawn.c
test-common/ostree-spawn.h
test-common/utils.c

Here are a few fixes I accumulated while working on #296. See the commit messages for details.

Assorted test fixes

---

eos-update-server/eos-update-server.c
test-common/httpd.c

Reasonable people may disagree about whether this is cleaner or not but I saw https://github.com/endlessm/eos-updater/commit/810a04b0fb126dc82c30a4e31c5efe33d294dd35 on #332  and thought “Hey, I think there's a way to do that”.
https://phabricator.endlessm.com/T33677

Use g_autoslist to clean up GSLists

---

.editorconfig
.gitignore
debian/control
eos-updater-ctl/meson.build
eos-updater-prepare-volume/meson.build
eos-updater/poll-common.c
eos-updater/tests/meson.build
libeos-updater-flatpak-installer/tests/meson.build
libeos-updater-util/tests/meson.build
meson.build
tests/meson.build

Prep work for https://phabricator.endlessm.com/T35247.

Miscellaneous cleanup
